# fetch-article.py
# Usage: python fetch-article.py <url> [--web]

import os, sys, re, json
import requests
from readability import Document
from bs4 import BeautifulSoup
from utils import (
    safe_slug, clean_author, get_title, get_author,
    load_config, get_input_folder, get_temp_folder,
    get_user_agent, get_ad_strip_markers, apply_phonetic_replacements,
    is_clipboard_domain, is_youtube_url, parse_reader_mode
)

INPUT_FOLDER = get_input_folder()
TEMP_FOLDER  = get_temp_folder()

BLOCK_INDICATORS = [
    'access to this page has been denied',
    'access denied',
    'you have been blocked',
    'please enable cookies',
    'checking your browser',
    'cloudflare',
    'captcha',
    'enable javascript',
    'robot or human',
    'unusual traffic',
    'verifying you are human',
    'verify you are human',
    'enable cookies',
    'browser check',
    'the request could not be satisfied',
    'request blocked',
    'reference #',
    'generated by cloudfront',
    'http error 403',
    '403 forbidden',
]

def is_steam_news_url(url):
    from urllib.parse import urlparse
    parsed = urlparse(url)
    return 'steampowered.com' in parsed.netloc and '/news/' in parsed.path

def fetch_steam_news(url):
    """Fetch a Steam news article via the ISteamNews API. Returns (title, author, text) or raises."""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    # Path looks like: /news/app/4743930/view/690885979774387816
    parts = parsed.path.strip('/').split('/')
    try:
        appid = parts[parts.index('app') + 1]
        gid   = parts[parts.index('view') + 1]
    except (ValueError, IndexError):
        raise ValueError(f'Could not parse appid/gid from Steam URL: {url}')

    api_url = (f'https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/'
               f'?appid={appid}&count=20&maxlength=0&format=json')
    r = requests.get(api_url, timeout=15)
    r.raise_for_status()
    items = r.json().get('appnews', {}).get('newsitems', [])

    # The store page view/ id and the API gid are unrelated identifier schemes,
    # and API item URLs are CDN paths that don't match the store URL.
    # Fetch og:title from the page and match on title instead.
    try:
        page = requests.get(url, timeout=15)
        from bs4 import BeautifulSoup as _BS
        og = _BS(page.text, 'html.parser').find('meta', property='og:title')
        page_title = og['content'].strip() if og and og.get('content') else ''
        # og:title is often "Game - Article Title - Steam News", strip suffixes
        for suffix in [' - Steam News', ' - Steam']:
            if page_title.endswith(suffix):
                page_title = page_title[:-len(suffix)].strip()
                break
        # Also strip game name prefix if present ("Guild Wars 3™ - Our Guild Wars Philosophy")
        if ' - ' in page_title:
            page_title = page_title.split(' - ', 1)[1].strip()
    except Exception:
        page_title = ''

    def _title_norm(t):
        return re.sub(r'\s+', ' ', t).strip().lower()

    item = None
    if page_title:
        item = next((i for i in items
                     if _title_norm(i.get('title', '')) == _title_norm(page_title)), None)
    if not item:
        raise ValueError(f'Article not found in API response (got {len(items)} items)')

    title  = item.get('title', 'Untitled')
    author = item.get('author', '').strip() or 'Unknown Author'
    raw    = item.get('contents', '')

    # Strip BBCode and Steam-specific markup
    text = raw
    # {STEAM_CLAN_IMAGE}/appid/hash.ext  — image refs, drop them
    text = re.sub(r'\{STEAM_CLAN_IMAGE\}/\S+', '', text)
    # [img]...[/img]
    text = re.sub(r'\[img[^\]]*\].*?\[/img\]', '', text, flags=re.DOTALL|re.IGNORECASE)
    # [url=...] link text [/url]  — keep the link text
    text = re.sub(r'\[url=[^\]]*\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[/url\]', '', text, flags=re.IGNORECASE)
    # [previewyoutube=...]...[/previewyoutube]
    text = re.sub(r'\[previewyoutube[^\]]*\].*?\[/previewyoutube\]', '', text, flags=re.DOTALL|re.IGNORECASE)
    # Remaining [tag] / [/tag] pairs — strip tags, keep inner text
    text = re.sub(r'\[/?\w[^\]]*\]', '', text)
    # HTML entities
    for ent, ch in [('&amp;', '&'), ('&lt;', '<'), ('&gt;', '>'),
                    ('&nbsp;', ' '), ('&#39;', "'"), ('&quot;', '"')]:
        text = text.replace(ent, ch)
    # Collapse excessive blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = text.strip()

    return title, author, text

def is_blocked(title, text):
    title_lower    = title.lower()
    combined_lower = (title + ' ' + text).lower()
    # Check title alone first — block pages often have very little body text
    if any(phrase in title_lower for phrase in BLOCK_INDICATORS):
        return True
    return any(phrase in combined_lower for phrase in BLOCK_INDICATORS) \
           and len(text) < 500

def fetch_article(url):
    os.makedirs(TEMP_FOLDER, exist_ok=True)
    os.makedirs(INPUT_FOLDER, exist_ok=True)

    if not url:
        # Direct clipboard/text mode — handoff file already written by caller
        handoff_path = os.path.join(INPUT_FOLDER, 'clipboard-handoff.json')
        if not os.path.isfile(handoff_path):
            print('  No clipboard handoff found.')
            sys.exit(1)
        with open(handoff_path, 'r', encoding='utf-8') as f:
            handoff = json.load(f)
        slug = handoff.get('clipboard_slug')
        # txt file already written by web_pipeline.py — nothing more to do
        print(f'  Slug:     {slug}')
        return slug

    elif is_youtube_url(url):
        print(f'  YouTube URL detected, will download audio directly.')
        from urllib.parse import urlparse, parse_qs
        parsed   = urlparse(url)
        video_id = parsed.path.lstrip('/') if 'youtu.be' in parsed.netloc \
                   else parse_qs(parsed.query).get('v', ['unknown'])[0]
        slug = f'youtube-{video_id}'
        with open(os.path.join(TEMP_FOLDER, f'youtube-handoff-{slug}.json'),
                  'w', encoding='utf-8') as f:
            json.dump({'youtube': True, 'source_url': url, 'slug': slug}, f)
        with open(os.path.join(TEMP_FOLDER, f'{slug}.json'),
                  'w', encoding='utf-8') as f:
            json.dump({'title': slug, 'artist': '', 'album': 'YouTube',
                       'album_art': None, 'slug': slug, 'source_url': url},
                      f, indent=2)
        print(f'  Slug:     {slug}')
        return slug

    elif is_steam_news_url(url):
        print('  Steam news URL detected, fetching via API.')
        try:
            title, author, text = fetch_steam_news(url)
        except ValueError as e:
            print(f'  Steam article not available via API ({e}). Please use Text mode and paste from Reader Mode.')
            sys.exit(2)
        except Exception as e:
            print(f'  Steam API request failed ({e}). Please use Text mode and paste from Reader Mode.')
            sys.exit(2)
        if not text:
            print('  Steam API returned empty article body. Please use Text mode and paste from Reader Mode.')
            sys.exit(2)
        text = apply_phonetic_replacements(text)
        slug = safe_slug(title)
        # Write handoff so fetch-metadata uses our already-resolved title/author/slug
        handoff = {
            'clipboard_title':  title,
            'clipboard_slug':   slug,
            'clipboard_author': author,
            'clipboard_site':   'Steam',
        }
        with open(os.path.join(INPUT_FOLDER, 'clipboard-handoff.json'),
                  'w', encoding='utf-8') as f:
            json.dump(handoff, f)
        header   = f'{title}\r\nWritten by {author}\r\n\r\n\r\n'
        txt_path = os.path.join(TEMP_FOLDER, f'{slug}.txt')
        with open(txt_path, 'w', encoding='utf-8', newline='\r\n') as f:
            f.write(header + text.replace('\n', '\r\n') + '\r\n[pause:3000]')
        print(f'  Title:      {title}')
        print(f'  Author:     {author}')
        print(f'  Slug:       {slug}')
        print(f'  Saved:      {txt_path}')
        return slug

    elif is_clipboard_domain(url):
        print('  Known unsupported site, switching to text mode.')
        sys.exit(2)

    else:
        headers = {'User-Agent': get_user_agent()}
        try:
            r = requests.get(url, headers=headers, timeout=15)
        except (requests.exceptions.ConnectionError,
                requests.exceptions.ChunkedEncodingError):
            print('  Connection failed, site may be blocking bots.')
            sys.exit(2)

        full_soup = BeautifulSoup(r.text, 'html.parser')

        if not r.text or len(r.text.strip()) < 200:
            print('  Page appears empty or JS-rendered.')
            sys.exit(2)

        try:
            doc  = Document(r.text)
            soup = BeautifulSoup(doc.summary(), 'html.parser')

            for tag in soup.find_all(['figcaption', 'figure']):
                tag.decompose()
            for tag in soup.find_all(class_=lambda c: c and any(
                x in c.lower() for x in ['caption', 'credit', 'hide-caption']
            )):
                tag.decompose()

            blocks            = []
            seen_fingerprints = set()
            for tag in soup.find_all(['p', 'blockquote']):
                text_content = tag.get_text(separator=' ', strip=True)
                if not text_content or len(text_content) < 4:
                    continue
                fingerprint = ' '.join(text_content.lower().split()[:8])
                if fingerprint in seen_fingerprints:
                    continue
                seen_fingerprints.add(fingerprint)
                if tag.name == 'blockquote':
                    lines        = text_content.splitlines()
                    text_content = '\r\n'.join(f'    {line}' for line in lines)
                blocks.append(text_content)

            text = '\r\n'.join(blocks)
            text = re.sub(r'(\r\n){3,}', '\r\n\r\n', text)

            for marker in get_ad_strip_markers():
                idx = text.find(marker)
                if idx != -1:
                    text = text[:idx].rstrip()
                    break

            title  = get_title(full_soup, doc)
            author = get_author(full_soup)

            if is_blocked(title, text):
                print('  Site appears to be blocking scraping.')
                sys.exit(2)

            slug = safe_slug(title)

            with open(os.path.join(TEMP_FOLDER, f'slug-handoff-{slug}.json'),
                      'w', encoding='utf-8') as f:
                json.dump({'slug': slug, 'title': title, 'author': author,
                           'source_url': url}, f, indent=2, ensure_ascii=False)

        except SystemExit:
            raise
        except Exception as e:
            print(f'  Readability error: {e}')
            sys.exit(2)

    text = apply_phonetic_replacements(text)
    header   = f'{title}\r\nWritten by {author}\r\n\r\n\r\n'
    txt_path = os.path.join(TEMP_FOLDER, f'{slug}.txt')
    with open(txt_path, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write(header + text + '\r\n[pause:3000]')

    print(f'  Title:      {title}')
    print(f'  Author:     {author}')
    print(f'  Slug:       {slug}')
    print(f'  Saved:      {txt_path}')
    return slug

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--web']
    if '--clipboard' in args:
        url = ''
    elif args:
        url = args[0]
    else:
        print('Usage: python fetch-article.py <url> [--web]')
        sys.exit(1)
    try:
        fetch_article(url)
    except SystemExit:
        raise
    except Exception as e:
        print(f'Error: {e}')
        sys.exit(1)